### ISSUE TITLE
Compact Party Frames

### ISSUE THREAD

**Issue by electricmenace** [ls-/ls_UI#13]
When in a raid group this happens.

2x [ADDON_ACTION_BLOCKED] AddOn 'oUF_LS' tried to call the protected function 'CompactPartyFrameMember1:Show()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
FrameXML\CompactUnitFrame.lua:290: in function `CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:248: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:100: in function <FrameXML\CompactUnitFrame.lua:47>

Locals:

**Comment by ls-** [comment]
This one is damn tricky, I get it sometimes too, but I've yet to track it down. Hopefully one day I'll fix it, it's on my NY wishlist, lol.

**Comment by electricmenace** [comment]
Check out these two. There are some debugging tricks inthe posts
I'll do some more research but yea Blizz really f. up with the whole tainted frames crap

http://us.battle.net/wow/en/forum/topic/4768689845
http://www.wowinterface.com/forums/showthread.php?p=274936

**Comment by ls-** [comment]
Thanks. Yeah, I've read those threads in the past.. But the problem with taint is that it's pretty random T_T I once managed to taint compact frames by just opening in-game config whilst in combat, luckily, fixed that one fast. This time though, I can run raids w/o any taints for weeks and then BAM! I get a 128MB fat taintLog file right after I join LFR.

**Comment by ls-** [comment]
This week I'll try commenting out few lines [here](https://github.com/ls-/oUF_LS/blob/master/modules/unitframes/units/party.lua#L23), cuz I use compact frame manager as an anchor o_O Might be or might not be the case.
