### ISSUE TITLE
ls_UI with OmniCC

### ISSUE THREAD

**Issue by arthurmelo88** [ls-/ls_UI#14]
Date: 2016-07-25 21:00:12
ID: 1
Error occured in: Global
Count: 1
Message: ...\AddOns\ls_UI\modules\unitframes\elements\totems.lua line 52:
   attempt to index field 'Timer' (a nil value)
Debug:
   ...\AddOns\ls_UI\modules\unitframes\elements\totems.lua:52: HandleTotems()
   ...ace\AddOns\ls_UI\modules\unitframes\units\player.lua:193: ConstructPlayerFrame()
   ls_UI\modules\unitframes\core.lua:91: styleFunc()
   ls_UI\embeds\oUF\ouf.lua:288:
      ls_UI\embeds\oUF\ouf.lua:218
   (tail call): ?
   ls_UI\embeds\oUF\ouf.lua:587: Spawn()
   ls_UI\modules\unitframes\core.lua:132: func()
   ls_UI\embeds\oUF\factory.lua:20:
      ls_UI\embeds\oUF\factory.lua:16
   (tail call): ?
Locals:
self = LSUnitFramesModule {
 0 = <userdata>
 CreatePvPIcon = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\pvp.lua:66
 CreateAltPowerBar = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\altpower.lua:55
 ConstructTargetFrame = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\units\target.lua:5
 Reskin = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\classpower.lua:276
 ConstructPlayerFrame = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\units\player.lua:5
 ConstructPetFrame = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\units\pet.lua:5
 HandleTotems = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\totems.lua:17
 CreateBuffs = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\auras.lua:247
 ConstructPartyFrame = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\units\party.lua:32
 CreateCastBar = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\castbar.lua:51
 CreateThreat = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\threat.lua:37
 CreateRuneBar = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\classpower.lua:421
 SetupArenaPrepFrames = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\units\arena.lua:261
 ConstructFocusFrame = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\units\focus.lua:5
 CreateHealPrediction = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\healprediction.lua:57
 CreateStaggerBar = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\classpower.lua:508
 ConstructArenaFrame = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\units\arena.lua:95
 SetupRarityIndication = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\rarityindication.lua:200
 framesByUnit = <table> {
 }
 ConstructBossFrame = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\units\boss.lua:12
 CreateDebuffs = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\auras.lua:266
 CreateStatusHighlight = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\highlight.lua:19
 CreateBossHolder = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\units\boss.lua:5
 ConstructFocusTargetFrame = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\units\focustarget.lua:5
 CreateHealthBar = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\health.lua:57
 CreateArenaHolder = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\units\arena.lua:88
 Initialize = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\core.lua:219
 CreatePowerBar = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\power.lua:57
 CreatePartyHolder = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\units\party.lua:17
 CreateClassPowerBar = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\classpower.lua:332
 ConstructTargetTargetFrame = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\units\targettarget.lua:5
}
parent = LSPlayerFrame {
 0 = <userdata>
 __tags = <table> {
 }
 UNIT_ENTERED_VEHICLE = <function> defined @Interface\AddOns\ls_UI\embeds\oUF\ouf.lua:38
 FloatingCombatFeedback = LSPlayerFrameFeedbackFrame {
 }
 mouseovers = <table> {
 }
 Cover = LSPlayerFrameCover {
 }
 PvP = <unnamed> {
 }
 __elements = <table> {
 }
 UNIT_THREAT_SITUATION_UPDATE = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\highlight.lua:7
 PLAYER_REGEN_DISABLED = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\highlight.lua:7
 PowerPrediction = <table> {
 }
 UNIT_THREAT_LIST_UPDATE = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\highlight.lua:7
 Power = LSPlayerFramePowerBar {
 }
 PLAYER_REGEN_ENABLED = <function> defined @Interface\AddOns\ls_UI\modules\unitframes\elements\highlight.lua:7
 HealPrediction = <tabl
AddOns:
  lsUI, v3.04
  lsWishlist, v1.05
  OmniCC, v7.0.1
  oUFLS, v3.04

**Comment by ls-** [comment]
Hi and thanks! I always forget about omniCC existence T_T

Fixed with https://github.com/ls-/ls_UI/commit/68988e9bdd3c15dd3508d3599e1826a3d7f2d35b.
