### ISSUE TITLE
Error on target Aura buff

### ISSUE THREAD

**Issue by arthurmelo88** [ls-/ls_UI#15]
Date: 2016-07-25 23:53:38
ID: -3
Error occured in: Global
Count: 2
Message: ..\AddOns\ls_UI\embeds\oUF\elements\aura.lua line 216:
   attempt to index field 'overlay' (a nil value)

**Comment by arthurmelo88** [comment]
I'm fixed with this code block on aura.lua `if icon.overlay then 
				if((isDebuff and icons.showDebuffType) or (not isDebuff and icons.showBuffType) or icons.showType) then
					local color = DebuffTypeColor[dtype] or DebuffTypeColor.none

					icon.overlay:SetVertexColor(color.r, color.g, color.b)
					icon.overlay:Show()
				else
					icon.overlay:Hide()
				end
			end`

**Comment by ls-** [comment]
No, that's not a good fix.

And tbh, that's pretty much impossible to get this issue. [button.overlay is ALWAYS created](https://github.com/ls-/ls_UI/blob/master/modules/unitframes/elements/auras.lua#L69-L74), unless someone modified aura button constructor T_T

**Comment by arthurmelo88** [comment]
this bug only happens with omnicc and when the aura will blink (or active another visual effect) on next 1 sec.
Example : I target myself and cast Eagle Eye (hunter).
when the eagle eye end, if I cast again with less then 1 sec of delay the aura blinks inside target buffs and the error appears.
![image](https://cloud.githubusercontent.com/assets/8607299/17126504/37a53caa-52d4-11e6-8651-1f914f81f655.png)

**Comment by ls-** [comment]
Ah, I see. Let me test it, if it's a conflict between oUF and OmniCC, there's nothing neither you nor I can and should do in this case. Then the best solutions will be to disable OmniCC for unit frame auras.

**Comment by ls-** [comment]
Okay, that's OmniCC bug. I'll report to tuller and jaliborc myself. It'll be much easier to explain what's going on.

**Comment by ls-** [comment]
K, reported it, for now stop using 'Activate' finish effect, use something else.

Closing this one.
