### ISSUE TITLE
Minimap button not skinning half the time

### ISSUE THREAD

**Issue by Ciraxe** [ls-/ls_UI#18]
The GameTimeFrame pretty much only gets skinned half the time. As I type this it's not fully skinned even after a reload. It sometimes takes a relog for it to fix itself. As of right now there's a blue box behind the button.

![button-error](https://cloud.githubusercontent.com/assets/450648/18809982/7b680ebe-8258-11e6-9305-0c5b03f3554d.png)

**Comment by ls-** [comment]
Hi again!

Ugh, I'm aware of this issue. Skinning works fine, but for some reason mask isn't applied to that texture sometimes.

This bug occurs randomly and infrequently, at least on my system, that's why it's quite difficult to debug it. I'll fix it, when I find the reason why it happens.

**Comment by ls-** [comment]
Hopefully fixed, but I'll release it a bit later.
