### ISSUE TITLE
bug..."WorldMapActionButton.lua"

### ISSUE THREAD

**Issue by laincat** [ls-/ls_UI#19]
1x [ADDON_ACTION_BLOCKED] 插件 'ls_UI' 尝试调用保护功能 '<unnamed>:SetEnabled()'。
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `SetEnabled'
FrameXML\WorldMapActionButton.lua:96: in function `UpdateCooldown'
FrameXML\WorldMapActionButton.lua:5: in function <FrameXML\WorldMapActionButton.lua:3>

Locals:

**Comment by laincat** [comment]
1x [ADDON_ACTION_FORBIDDEN] 插件 'ls_UI' 尝试调用保护功能 'SpellStopTargeting()'。
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `SpellStopTargeting'
FrameXML\WorldMapActionButton.lua:61: in function `Clear'
FrameXML\WorldMapActionButton.lua:67: in function `Refresh'
ls_UI\modules\blizzard\worldmap.lua:61: in function `Refresh'
FrameXML\WorldMapActionButton.lua:26: in function `SetHasWorldQuests'
FrameXML\WorldMapFrame.lua:872: in function <FrameXML\WorldMapFrame.lua:822>
[C]: in function `WorldMap_UpdateQuestBonusObjectives'
FrameXML\WorldMapFrame.lua:1142: in function `WorldMapFrame_Update'
FrameXML\WorldMapFrame.lua:2869: in function `WorldMapFrame_UpdateMap'
FrameXML\WorldMapFrame.lua:408: in function <FrameXML\WorldMapFrame.lua:394>
[C]: in function `ZoomOut'
FrameXML\WorldMapFrame.lua:2119: in function `WorldMapZoomOutButton_OnClick'
FrameXML\WorldMapFrame.lua:2148: in function <FrameXML\WorldMapFrame.lua:2130>
(tail call): ?
(tail call): ?

Locals:
nil

**Comment by laincat** [comment]
1x [ADDON_ACTION_FORBIDDEN] 插件 'ls_UI' 尝试调用保护功能 'UseWorldMapActionButtonSpellOnQuest()'。
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `UseWorldMapActionButtonSpellOnQuest'
FrameXML\WorldMapFrame.lua:1826: in function <FrameXML\WorldMapFrame.lua:1822>

Locals:
nil

**Comment by ls-** [comment]
Hi!

c3fd09067b4f47c4166999c39b05af8d6035da13, 0d9209973a49b467518bf91f9fcdc567e0b8aa1c, and f9c74dcfdad8330e329abf6bc8d8f82c4eb178ee "fixed" it. I simply gutted everything that was tainting blizz code, unfortunately, there's no other way to fix it 💩

Have a nice day 👍
