### ISSUE TITLE
GetAttribute still exists unfortunately enough

### ISSUE THREAD

**Issue by Ciraxe** [ls-/ls_UI#20]
Message: Interface\AddOns\ls_UI\modules\tooltips\tooltips.lua:369: attempt to call method 'GetAttribute' (a nil value)
Time: 11/27/16 20:52:50
Count: 1

**Comment by ls-** [comment]
Holy.... There's one place with `GetAttribute` call T_T Will push an update a bit later today :(

**Comment by ls-** [comment]
Released the fix as 70100.02.

Thanks, and have a nice day 👍
