### ISSUE TITLE
Grow direction option for Bossframe

### ISSUE THREAD

**Issue by p5hema2** [ls-/ls_UI#23]
Can you implement an option the the bossframe can grow upwards. 

And in addition that we ca place the castbars left or right.

**Comment by ls-** [comment]
Hi!

Hm, growth direction option sounds like a good idea, not so sure about castbar placement though, and here's why. As you might have guessed I'm in the middle of unit frame redesign, so I'm not that eager to fix anything uf-related right now, cuz it'll be a waste of time. I haven't decided on castbar's position, so can't say anything about options for it T_T

**Comment by ls-** [comment]
![](https://i.imgur.com/aqjoSAH.png?2)

Done: https://github.com/ls-/ls_UI/commit/15e1ad1fe335db8df292d6e16bc51697fcb9efc2
