### ISSUE TITLE
Honor bar generates LUA error

### ISSUE THREAD

**Issue by heinzmuller** [ls-/ls_UI#24]
When right clicking the honor bar in the Honor Talents and selecting the show as XP bar option I get this LUA error and it persists until I uncheck the XP bar option

```
Message: Interface\AddOns\ls_UI\modules\bars\xpbar.lua:161: attempt to index field 'line3' (a nil value)
Time: Tue Feb  7 19:35:26 2017
Count: 1
Stack: Interface\AddOns\ls_UI\modules\bars\xpbar.lua:161: in function <Interface\AddOns\ls_UI\modules\bars\xpbar.lua:51>
Interface\AddOns\ls_UI\modules\bars\xpbar.lua:472: in function `func'
Interface\FrameXML\UIDropDownMenu.lua:787: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
```

**Comment by ls-** [comment]
Hi!

I can't push/release any updates now, hope you're willing to do it manually, here's how:
- Open file ["\Interface\addons\ls_UI\modules\bars\xpbar.lua" at line 161](https://github.com/ls-/ls_UI/blob/d0c621d7aee4543a683ee684bd39434e10995052/modules/bars/xpbar.lua#L161);
- Replace it with this code:
```Lua
bar[index].tooltipInfo.line3 = {
	text = L["XP_BAR_HONOR_BONUS_TOOLTIP"]:format(_G.GetHonorExhaustion())
}
```
- Save & /reload.

I guess I was really tired when I was writing that line of code T_T

**Comment by heinzmuller** [comment]
Worked wonders :)

I'll be eagerly waiting for the updated UI with the new Minimap!

**Comment by ls-** [comment]
Fixed. Will release an update within next few days.
