### ISSUE TITLE
Player unit frame with the same style as target frames?

### ISSUE THREAD

**Issue by Gotxiko** [ls-/ls_UI#25]
I really love the target frames and I wonder if you will implement an option to make the unit frame "orb" to look like the target frame? Thank you, and great job!

**Comment by ls-** [comment]
That's gonna be my next step in UF overhaul.

I'm planning to design new target and other UFs, and then I'm going to create optional UI style w/ more traditional UI layout. However, I need to design new target frames first.

ATM I'm working on ls: Toasts, can't do multiple things at once :D

**Comment by Gotxiko** [comment]
In the meantime I replaced the UF:ConstructTargetFrame from target.lua to player.lua and it works just fine. (But without runes ofc).
![a](https://cloud.githubusercontent.com/assets/416493/23105267/d6fa1cd8-f6dc-11e6-8c7c-b7f5b7c11c63.png)
