### ISSUE TITLE
Quests and artifact/experience/reputaion bars

### ISSUE THREAD

**Issue by marcuslma** [ls-/ls_UI#27]
Hello, thank you for this awesome work!
However, I am experiencing some bugs (or not).
So, first of all, some times some quests are not being shown over the NPC's head.
I notice that they have quest by putting my mouse over they or some times because I see it on the minimap.
Second issue is that I am trying to activate the 3 bars on my characters Artifact Power, Experience and Reputation. There is always 2 bars active, Arctifact Power and Experience, but the third bar (Reputation) it is shown for a short time and disappears.
Could you investigate this?
Thank you very much!

**Comment by ls-** [comment]
Sup!
>So, first of all, some times some quests are not being shown over the NPC's head.
My UI doesn't have nameplates and does nothing to NPC names whatsoever, so it's either Blizz bug or it's some other addon.

As for reputations. There's a "bug" on Blizz side, there's a massive lag when you enable or disable reputation tracking, I should prob talk to Blizz devs about it, hehe, cuz quite many people reported this issue, but solution is quite simple: if you track reps via shift-clicking shift click it once and wait a bit, if you do so via clicking the "Show as Exp Bar" checkbox, click it once and wait a bit.

TBF, rep tracking issue has been in game since forever.

If it's something else, please, let me know :p

**Comment by marcuslma** [comment]
Thanks for the quick answer.
> My UI doesn't have nameplates and does nothing to NPC names whatsoever, so it's either Blizz bug or it's some other addon.
I just am using your UI, so maybe it is a Blizz bug, I will try to repair the game. I reported this to you because it started after using your UI, or not, maybe that was happening for a while I just noticed this now.
So, about the reputation bar, I always activate it by the "Show as Exp Bar" checkbox, but after some seconds it auto unchecks, and I reported it because it only happens with your UI (I am sure about this one hehe).
Thanks for your attention! And again, great job!

**Comment by ls-** [comment]
K, I reported the "bug", but I'm not sure if it's gonna be fixed, it's been in game since Vanilla, I honestly dunno why people started noticing it only now.

I guess it's implemented this way due to some communication limitations, dunno if current dev team is going to revisit/investigate it :p

**Comment by marcuslma** [comment]
Hehehe!
Thanks bro.
And let me now if they answer something!

**Comment by ls-** [comment]
Yeah, I will. But I have a feeling that it's some lowprio issue that's on the bottom of their bug list :D

**Comment by marcuslma** [comment]
I had disabled your ui and I figured out that on vanilla ui we can't have the artifact and reputation bar at the same time.
So I let activated the reputation bar and enabled again your ui and now the three bars are being shown correctly.
It says something to you?
I don't want to bother you bro, just telling you some results!
Bye!

**Comment by ls-** [comment]
I know that you can't have 3 bars in Vanilla UI, that why I decided to do it in my UI the way I did.

I can easily reproduce this "bug" by double clicking the checkbox:
![image](http://i.imgur.com/VIM5R5S.gif)

You simply have to wait till it's enabled or disabled T_T It's a known issue, sometimes it gets worse sometimes it's almost nonexistent. I guess it depends on server load or whatever is the reason behind this lag.
