### ISSUE TITLE
70200.07

### ISSUE THREAD

**Issue by Gotxiko** [ls-/ls_UI#30]
```
Message: Interface\AddOns\ls_UI\core\constants.lua:58: attempt to index local 'oUF' (a nil value)
Time: 05/21/17 15:00:07
Count: 1
Stack: Interface\AddOns\ls_UI\core\constants.lua:58: in main chunk
```
That's the first of 30 errors.

:)

**Comment by ls-** [comment]
WTF O_o

**Comment by ls-** [comment]
Did you restart the client?

**Comment by Gotxiko** [comment]
Deleted WTF and reinstalled the addon.
 Now it works, something I messed up seems.

**Comment by ls-** [comment]
Damn, son, after 70200.05 fiasco I tested this update quite extensively, don't scare me :D
