### ISSUE TITLE
Aura tracker suggestion

### ISSUE THREAD

**Issue by Gotxiko** [ls-/ls_UI#31]
Would it be much of a trouble to leave the aura tracker as it is now? I know you want to remove it, but I find it very useful and easily customizable. Weakauras is a pain in the ass for me :(

No need to touch it more, just leave it as it is.

**Comment by ls-** [comment]
I do know that some people like it, even I used it on one of my char where fancy aura tracking isn't that necessary :D 

I'll disable it by default and add a warning that it's a deprecated feature, but I won't remove it, that's my current plan.

**Comment by ls-** [comment]
@Gotxiko, you're lucky, kinda.

![image](http://i.imgur.com/FyLqnCZ.png)

I rewrote aura tracker config. There's one difference though, you want be able to set specs for auras. New  aura tracker will use one config PER CHARACTER, I personally don't think that adding it to every single profile is a good idea. The only downside is that it's not transferable as in it's not affected by profile changes at all.

Any ideas?

**Comment by Gotxiko** [comment]
I don't think it's a problem not being able to filter per spec. I think specs don't really share procs besides the most important ones like Concordance and/or trinkets.

I think it's looking great :)

**Comment by ls-** [comment]
And I guess one almost always wants to see these important procs on any spec :D 

Anyways, I'm closing this ticket.
