### ISSUE TITLE
Auras.lua

### ISSUE THREAD

**Issue by Ciraxe** [ls-/ls_UI#32]
Message: ...e\AddOns\ls_UI\modules\unitframes\elements\auras.lua:173: attempt to index field 'filter' (a nil value)
Time: 09/24/17 21:18:01
Count: 5
Stack: ...e\AddOns\ls_UI\modules\unitframes\elements\auras.lua:173: attempt to index field 'filter' (a nil value)
[C]: ?
...e\AddOns\ls_UI\modules\unitframes\elements\auras.lua:173: in function <...e\AddOns\ls_UI\modules\unitframes\elements\auras.lua:166>
Interface\AddOns\ls_UI\embeds\oUF\elements\auras.lua:182: in function <Interface\AddOns\ls_UI\embeds\oUF\elements\auras.lua:140>
Interface\AddOns\ls_UI\embeds\oUF\elements\auras.lua:275: in function <Interface\AddOns\ls_UI\embeds\oUF\elements\auras.lua:269>
Interface\AddOns\ls_UI\embeds\oUF\elements\auras.lua:350: in function <Interface\AddOns\ls_UI\embeds\oUF\elements\auras.lua:296>
(tail call): ?

This error is popping up while killing things on a fresh hunter. It's not happening every kill but, moreso like every 3 kills.

**Comment by Ciraxe** [comment]
It appears I have fixed the issue to where it doesn't error for me anymore. I enabled then disabled the aura tracker and then reloaded ui. Debuffs now show on the target like it was supposed to.

**Comment by ls-** [comment]
Hmmm... I'll look into it o_O

**Comment by ls-** [comment]
I have a feeling that it's just some weird SV (saved variables) bug...

**Comment by Ciraxe** [comment]
It might indeed be some SV bug but, cannot test right now as my grandmother just passed earlier today and there's really no time to be playing games atm. I'll make sure to post more when I do get to the testing.

**Comment by ls-** [comment]
@Ciraxe, my condolences. Take your time.

I'm struggling w/ dengue fever atm, so I'm in no condition to do a lot work either.

**Comment by Ciraxe** [comment]
Needed to get my mind of things so I did some testing. Tried new characters on servers where I already had toons as well as new toons on servers I did not and I could not reproduce the errors. It must've been some fluke SV error.

**Comment by ls-** [comment]
I'll close it then.
