### ISSUE TITLE
Requests/Ideas

### ISSUE THREAD

**Issue by Solence1** [ls-/ls_UI#37]
Would love to have the option to change healtbar texture and maybe ad an option for an portaitframe in bosses/targets etc.

**Comment by ls-** [comment]
Sup!

The issue w/ health bars' "textures" is that I don't really use textures for them, it's just flat colours.

As for portraits, I dunno, I never actually liked the idea of having them, but let's say I decide to add them, do you have any examples of how they should be look like, e.g., a separate inset frame, a separate frame outside the unit frame, a health bar overlay, etc?

**Comment by Solence1** [comment]
1. Alright got it.

2.  I would only really care for bossframe portraits to quickly have a glance on council fights what frame i am looking at. The other frames where just an extension of said idea.^^
 Thats what i thought it could look like: http://prntscr.com/jmue9l

**Comment by ls-** [comment]
>When i target something via the boss frames i'd like to have an target indicator around the frame via glow or something like that.

Eh? Glow effect is used as the threat display. Anyway, do you want to have something like a current target indicator on the boss frame? I think it's the first time I'm seeing anyone suggesting it for a non-nameplate unit frame :D 

>Is it possible to change the threat glow color ?

At some point in the future I'm planning to add colour overrides, but right now it relies on Blizz threat API.
