### ISSUE TITLE
Only the player and pet UF are loading

### ISSUE THREAD

**Issue by Gotxiko** [ls-/ls_UI#39]
The rest of the UF and castbars are not loading in this latest version.
Runes on the player UF are not showing either.

On the "Orbs" mode, all the UF seem to load.

**Comment by ls-** [comment]
Hmm.... I'll test it when I get back home, ty.

**Comment by ls-** [comment]
Drycoded it, but it's an easy fix .Will release 80000.02 when I get back home.

**Comment by Gotxiko** [comment]
Thank you! :D
