### ISSUE TITLE
Significant bug in text format handling

### ISSUE THREAD

**Issue by klaxce** [ls-/ls_UI#40]
If you put an incorrect text tag in the Format field of the Target Frame Power element then you can cause the minimap to not be reskinned/repositioned, as well as unable to edit the Focus, Target of Focus and Boss Frames. You may have to reload/relog after applying the incorrect text formatting in order for it to break things.

ex. ``[ls:color:power][ls:power:perc]`` works and everything is fine, but if you do ``[ls:power:color][ls:power:perc]`` then it breaks things as described (power/color are reversed).

I haven't tested this in other Format fields.

**Comment by ls-** [comment]
Hm, I'll test it a bit later today...

TY for the report <3

**Comment by ls-** [comment]
Got it.

`[ls:power:color]` isn't a legit tag, so when you try to use it this error:
```1x ...acels_UI\modules\unitframes\units\player-Player.lua:36: Attempted to use invalid tag [ls:power:color].```

Technically, it's not a bug, it's the intended behaviour. I may add tag string validation though...

**Comment by ls-** [comment]
On a side note, you should prob install BugSack and BugGrabber, by default, Blizz lua error reporting is disabled.

**Comment by klaxce** [comment]
The expected behavior of a malformed tag shouldn’t be to break half of the addon. So anything that stops that would be great. To be fair, I didn’t actually have Lua errors turned on and so it took me a few profile resets to figure out what was causing the addon to break. I hadn’t realized that the tags were static and not dynamically accepting arguments, so I had tried to shorten my tag to set power text and color in one tag.   
  

  
  

  
  
>

**Comment by ls-** [comment]
K, now if you try to use something like this: `[ls:health:cur][tag #1] [tag #2]`, tag setter won't update the string, and you'll see a message like this in the config's status bar:
![Imgur](https://i.imgur.com/LL4fu5i.png)
