### ISSUE TITLE
Achievement UI Error

### ISSUE THREAD

**Issue by FortyOneNY** [ls-/ls_UI#43]
My ls_UI version is 80100.04. If I hide the Achievement micro button (by unchecking "Show" in the Micro Button > Achievements menu) and then attempt to open the Achievement UI via hotkey, the Achievement UI will show and work but it throws an error:

1x ...ns\Blizzard_AchievementUI\Blizzard_AchievementUI-1.0.lua:847: attempt to call global 'AchievementMicroButton_Update' (a nil value)
...ns\Blizzard_AchievementUI\Blizzard_AchievementUI-1.0.lua:847: in function <...ns\Blizzard_AchievementUI\Blizzard_AchievementUI.lua:788>
[C]: ?
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:446: in function <FrameXML\UIParent.lua:445>
[C]: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:561: in function `AchievementFrame_LoadUI'
FrameXML\UIParent.lua:747: in function `ToggleAchievementFrame'
[string "TOGGLEACHIEVEMENT"]:1: in function <[string "TOGGLEACHIEVEMENT"]:1>

Locals:
self = AchievementFrameAchievements {
 0 = <userdata>
 forceOnShow = <function> defined @Blizzard_AchievementUI\Blizzard_AchievementUI.lua:697
}
event = "ADDON_LOADED"
(*temporary) = nil
(*temporary) = "attempt to call global 'AchievementMicroButton_Update' (a nil value)"
updateTrackedAchievements = <function> defined @Blizzard_AchievementUI\Blizzard_AchievementUI.lua:81
IN_GUILD_VIEW = nil
trackedAchievements = <table> {
}
guildMemberRequestFrame = nil

**Comment by ls-** [comment]
Hm, I'll look into it, when I get back home >_>

**Comment by FortyOneNY** [comment]
I thought that might be the case, but I wasn't sure. Thanks for looking into it!

**Comment by ls-** [comment]
Added a hack for this issue w/ 80100.05, so it should be safe to hide the button now.
