### ISSUE TITLE
Classic support?

### ISSUE THREAD

**Issue by Gotxiko** [ls-/ls_UI#45]
Just wondering if you will work on supporting lsUI and Toasts for Classic or if they work now without many changes. :P

**Comment by ls-** [comment]
Sup o/

I might update toasts for Classic, from what I've seen so far it may actually work as is, even if they change something, it's a minute amount of work :D

As for my UI, def nope. I'm not going to play WoW Classic, so spending THAT MUCH time on something I won't even use is a waste, I mean, I hardly have enough spare time to work on the retail version of the UI 😭

**Comment by Gotxiko** [comment]
Thanks for letting me know :D 
It'd be great if you could make Toasts work, it's become a must-have feature for me since I installed it. Regarding the UI, will have to try and "replicate" it using bartender and stuff ;)
Thanks for all the work!

**Comment by ls-** [comment]
@Gotxiko, toasts for classic are [here](https://github.com/ls-/ls_Toasts/tree/dev-classic).
