### ISSUE TITLE
Plans to support Shadowlands

### ISSUE THREAD

**Issue by jmauss** [ls-/ls_UI#53]
Hi, not necessarily an issue but was just wondering if support will be continued for Shadowlands? This is by far my favorite UI addon and, if you have a place to donate, I would love to send some support your way. Thanks for all the work!

**Comment by ls-** [comment]
Sup!

Yes, just pushed [the update](https://github.com/ls-/ls_UI/releases/tag/90001.01), pushed it to curse and wowi as well. Sadly, no new features, I was hospitalised for a couple of months and will be going back to the hospital by the end of this week once again. Honestly, I could only focus on working on 1 thing, so I chose to write stuff  for oUF, whereas all my other projects were kinda ignored. Soz about that.
