### ISSUE TITLE
Issue when displaying health text

### ISSUE THREAD

**Issue by Gotxiko** [ls-/ls_UI#54]
Hey lightspark! Don't know if this is an issue with LS:UI or an issue with any other addon I have, but here it goes:

Health text on unit frames is not updating unless I deselect the target and select it again. Health text only gets updated when targeting, not when their health changes. Got this errors at some point while fighting, don't know if it's related.

```
Message: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:470: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
Time: Wed Oct 14 19:40:01 2020
Count: 1
Stack: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:470: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
[string "=[C]"]: in function `GetLeft'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:470: in function `GetPreferredInsets'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:166: in function `UpdateInsetsForType'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:150: in function `ApplyFrameOptions'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:116: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: (*temporary) = <unnamed> {
 otherHealPrediction = <unnamed> {
 }
 b = 0
 myHealAbsorbLeftShadow = <unnamed> {
 }
 border = <unnamed> {
 }
 background = <unnamed> {
 }
 overAbsorbGlow = <unnamed> {
 }
 barTexture = <unnamed> {
 }
 0 = <userdata>
 r = 0.999998
 totalAbsorb = <unnamed> {
 }
 myHealPrediction = <unnamed> {
 }
 g = 0
 totalAbsorbOverlay = <unnamed> {
 }
 myHealAbsorbRightShadow = <unnamed> {
 }
 overHealAbsorbGlow = <unnamed> {
 }
 myHealAbsorb = <unnamed> {
 }
}

```

```
`Message: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:216: Usage: GetRaidTargetIndex(unit)
Time: Wed Oct 14 19:40:49 2020
Count: 6
Stack: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:216: Usage: GetRaidTargetIndex(unit)
[string "=[C]"]: in function `GetRaidTargetIndex'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:216: in function `OnRaidTargetUpdate'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:122: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: (*temporary) = nil
`
```

```
`Message: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:216: Usage: GetRaidTargetIndex(unit)
Time: Wed Oct 14 19:40:49 2020
Count: 6
Stack: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:216: Usage: GetRaidTargetIndex(unit)
[string "=[C]"]: in function `GetRaidTargetIndex'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:216: in function `OnRaidTargetUpdate'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:122: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: (*temporary) = nil
`
```

**Comment by ls-** [comment]
Errors are unrelated, I don't do anything with nameplates, so it's some other addon for sure. I'll look into health text, seems weird

**Comment by Gotxiko** [comment]
Will have a look at my addons and see if/what is conflicting...

**Comment by ls-** [comment]
BTW, have you ever edited tags via config?

**Comment by ls-** [comment]
Seems like I'm not investigating anything today, and if I log in manually after sitting in the queue for >5 minutes I get booted. Ah, big patches/expansions are such a pain 😒🔫 
![image](https://user-images.githubusercontent.com/2725970/96026863-4835fd80-0e81-11eb-83f7-2381acceda8f.png)

**Comment by Gotxiko** [comment]
Tried disabling addons, other addons don't seem to be conflicting.

I believe the tag is correct, and it's not only this one, tried with other tags and are not updating either.

UNIT_MAXHEALTH UNIT_CONNECTION PLAYER_FLAGS_CHANGED

function(unit)
  if not UnitIsConnected(unit) then
    return _VARS.L["OFFLINE"]
  elseif UnitIsDeadOrGhost(unit) then
    return _VARS.L["DEAD"]
  else
    return _VARS.E:FormatNumber(UnitHealth(unit))
  end
end

**Comment by ls-** [comment]
Seems really weird. I played earlier today, everything worked fine O_o

**Comment by Gotxiko** [comment]
Tried on more than one character as well, as well as disabling all addons besides lsui, problem persists. It's really weird.

Patience with that queue! Take your time, not really a critical problem right now ;)

**Comment by ls-** [comment]
And you aren't getting any errors?

**Comment by Gotxiko** [comment]
No errors whatsoever, the numbers just don't update unless I "re-target" the objective.

**Comment by ls-** [comment]
I AM RETARDED. I FORGOT TO PUSH 1 CHANGE! FFS...

**Comment by Gotxiko** [comment]
Hahaha it happens! Glad you could find the problem :D

**Comment by ls-** [comment]
Lemme grab some tea and see if I missed anything else, and I'll release and update.

**Comment by Gotxiko** [comment]
I'll close this issue then :)
Thank you!
