### ISSUE TITLE
Any way to change fonts?

### ISSUE THREAD

**Issue by waio1990** [ls-/ls_UI#56]
Hello, love the UI, I just wish there was a way to change the default font, maybe another addon can do the job but I don't know about one that changes those.

Thanks!!

**Comment by ls-** [comment]
Hi, unfortunately, currently there's none, it's a self-imposed limitation >_> I'm planning to move to LSM in the near future that will address the issue, it'll probably be the first thing I'm gonna do after I get out of the hospital.

**Comment by ls-** [comment]
I've started working on it today, so I'll be closing this ticket.
