### ISSUE TITLE
[Error] Colorwheel error on color editor (General->Colors)

### ISSUE THREAD

**Issue by Gotxiko** [ls-/ls_UI#58]
When clicking on any point in this selector (red), it gives the following error. On some options the error does not show up, it errors out mainly on options that affect the color of any of the elements of the Player UF.

![1](https://user-images.githubusercontent.com/416493/99983173-ce603080-2dab-11eb-9964-221ece776f87.PNG)

> Message: ...\AddOns\ls_UI\modules\unitframes\elements\health.lua:79: attempt to index field '_config' (a nil value)
> Time: Mon Nov 23 16:49:13 2020
> Count: 224
> Stack: ...\AddOns\ls_UI\modules\unitframes\elements\health.lua:79: attempt to index field '_config' (a nil value)
> [string "@Interface\AddOns\ls_UI\modules\unitframes\elements\health.lua"]:79: in function `?'
> [string "@Interface\AddOns\ls_UI\modules\unitframes\core.lua"]:93: in function `?'
> [string "@Interface\AddOns\ls_UI\modules\unitframes\core.lua"]:224: in function `UpdateUnitFrame'
> [string "@Interface\AddOns\ls_UI\modules\unitframes\core.lua"]:247: in function `ForEach'
> [string "@Interface\AddOns\ls_UI\config\general.lua"]:783: in function <Interface\AddOns\ls_UI\config\general.lua:774>
> [string "=[C]"]: ?
> [string "@Interface\AddOns\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
> [string "@Interface\AddOns\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
> [string "=[C]"]: ?
> [string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
> [string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:306: in function `Fire'
> [string "@Interface\AddOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-ColorPicker.lua"]:28: in function <...Ace3\AceGUI-3.0\widgets\AceGUIWidget-ColorPicker.lua:21>
> [string "@Interface\AddOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-ColorPicker.lua"]:60: in function `func'
> [string "*:OnColorSelect"]:3: in function <[string "*:OnColorSelect"]:1>
> 
> Locals: <none>

**Comment by ls-** [comment]
Hmmmm... I couldn't reproduce it >_> Does it still happen?

**Comment by Gotxiko** [comment]
Updated to the last version just in case, error is still showing up. Not sure what could be causing it.

It's not urgent for me as I don't really need to change colors for the ones that error out.

Tried disabling addons that could be interfering, but the error still happening.

**Comment by Gotxiko** [comment]
After this last commit the problem is solved. Closing issue 👍
