### ISSUE TITLE
Torghast Map does not work on square minimap

### ISSUE THREAD

**Issue by OgulcanCelik** [ls-/ls_UI#59]
Hello!

Loving the addon, however, there is a slight problem with minimap on Torghast, it does not work! It does work anywhere else or works on Torghast on normal circle mode.

![image](https://user-images.githubusercontent.com/7064011/100396718-2e2e3400-3057-11eb-862b-42d62a2bf4be.png)

**Comment by ls-** [comment]
I feel soooooo retarded, I completely forgot to update my minimap for Torghast T_T I'll look into it tomorrow.

**Comment by ls-** [comment]
Should be fixed now. I'll release an update shortly.
