### ISSUE TITLE
Amazing API

### ISSUE THREAD

**Issue by greven** [ls-/ls_UI#60]
Hey mate,

This is not really an issue but as I don't see the discussion tab open.

Just wanted to thank you.
I'm the author of oUF_Lumen, but since my code had so many holes and tech debt throughout a decade of the layout now, I really wanted to start over fresh, and re-write my  whole UI from scratch. Because re-writing everything is such a major endeavour I was looking for a layout to base my code and re-use APIs, code organization, etc.

I have been following ls_UI for quite awhile but now that I'm using large part of it to write my own UI, I have to say the code structure is delightful. 👍 

So, this is not an issue, just a thank you. :)

You can close it! <3

**Comment by ls-** [comment]
@greven Thanks! Oof, there's older parts of the codebase that are godawful, I have a huge todo list for the future >_> So good luck with that :D

**Comment by greven** [comment]
Code always needs re-writing. But the parts I've been using is your oUF parts around the callbacks. That's a pretty good way to structure the layout. The way I had it was way more imperative. 👍

Might have some little bugs I've found, so will defo tryout your layout to see if it's me or some bugs, specially around the GainLoss Indicators for Power. But I will try out your UI to test!

Thanks again mate. :) Will close this as this really not an issue.
