### ISSUE TITLE
Lua Error issue

### ISSUE THREAD

**Issue by lynspottery** [ls-/ls_UI#61]
I was turning in a quest for the Night Fae Assault in the maw today and got the following lua error message.  Since I use this addon, I thought you might have some idea what its referring to.
-----------------------------------------------------------------
Message: Interface\FrameXML\QuestInfo.lua:1074: Invalid quest item in SetQuestItem("type", index)
Time: Sun Jul 18 14:44:23 2021
Count: 1
Stack: Interface\FrameXML\QuestInfo.lua:1074: Invalid quest item in SetQuestItem("type", index)
[string "=[C]"]: in function `SetQuestItem'
[string "@Interface\FrameXML\QuestInfo.lua"]:1074: in function <Interface\FrameXML\QuestInfo.lua:1059>

Locals: (*temporary) = GameTooltip {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @Interface\SharedXML\Backdrop.lua:205
 GetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:443
 SetHyperlink = <function> defined =[C]:-1
 RightEdge = <unnamed> {
 }
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:335
 Show = <function> defined =[C]:-1
 SetLootCurrency = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:267
 HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:331
 GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:241
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 SetCurrencyByID = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 progressBarPool = <table> {
 }
 SetCurrencyToken = <function> defined =[C]:-1
 updateTooltipTimer = 0.020000
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:475
 SetArtifactPowerByID = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 ClearLines = <function> defined =[C]:-1
 SetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:382
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:400
 SetUnitDebuff = <function> defined =[C]:-1
 hasMoney = 1
 SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:319
 SetToyByItemID = <function> defined =[C]:-1
 widgetContainer = <unnamed> {
 }
 0 = <userdata>
 ApplyBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:347
 comparing = false
 waitingForData = false
 TextLeft1 = GameTooltipTextLeft1 {
 }
 ItemTooltip = <unnamed> {
 }
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:235
 SetUnitBuff = <function> defined =[C]:-1
 SetLFGDungeonReward = <function> defined =[C]:-1
 TopLeftCorner = <unnamed> {
 }
 textRight1Font = "GameTooltipHeaderText"
 TextRight1 = GameTooltipTextRight1 {
 }
 BottomEdge = <unnamed> {
 }
 SetAction = <function> defined =[C]:-1
 textLeft2Font = "GameTooltipText"
 SetCurrencyTokenByID = <function> defined =[C]:-1
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetUnitAura = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 backdropInfo = <table> {
 }
 needsReset = true
 SetupPieceVisuals = <function> defined @Interface\SharedXML\Backdrop.lua:299
 TopRightCorner = <unnamed> {
 }
 BottomOverlay = <unnamed> {
 }
 SetRecipeResultItem = <function> defined =[C]:-1
}
(*temporary) = "reward"
(*temporary) = 1

**Comment by ls-** [comment]
Unrelated.
