### ISSUE TITLE
UI freezes up when entering Raid/Dungeon/Instance

### ISSUE THREAD

**Issue by lynspottery** [ls-/ls_UI#62]
Several times this past week my LS: UI has frozen up whenever I've entered a raid, dungeon, or instance.   The normal method to fix issues like this is to /reload UI, but even that failed to unfreeze the UI and I've had to actually log out of the game completely.  In one instance, I actually had to reboot my pc to get it to unfreeze...even after trying the other two options.

This has only started happening when the new Zereth Mortis zone went live recently.  I always check my updates and currently am running the latest update posted.  I have no idea why your UI is suddenly freezing up because I've not changed anything about it.   However, on the off chance one of my current addons might have had an update that conflicts with your UI, I disabled all of them, leaving this UI the only addon running to test it by itself.  It seemed to do ok, but on one occasion while testing it, it seemed to stall then right itself.  

The worst time was this past Friday when my raid group started the new raid and nothing on the UI would work at all after entering the raid area.  Nothing I tried worked and I had to log out of the game and relaunch the game.  Once I did that, the UI started working again.  But I have to say that halfway through the raid I had some lack of response from some keys which seemed to stutter before returning to normal functionality.  

Sunday early afternoon while running Timewalking dungeons, it happened twice in the same instance, different boss.  Then again later  Sunday evening it occurred again when entering another Timewalking dungeon to finish the weekly, only this time I had to actually reboot my pc since the relaunch of the game failed to fix it.

**Comment by ls-** [comment]
Hi!
This is really awkward, and it's the first time I'm hearing about anything like that. I've never experienced it myself and neither did people I know who also use this UI.
Could you try reverting back to [90105.06](https://github.com/ls-/ls_UI/releases/tag/90105.06)?

**Comment by lynspottery** [comment]
Thank you for your response.  I had this happen again the day after I wrote this note to you.  So I totally uninstalled the UI then cleared out any mention in my folders including the savedvariables elsewhere in the other folders too.  I did not realize how much was saved from things I used...so this was quite an undertaking.  So to make sure I caught everything, I made copies of my WTF and Interface folders and saved them to my desktop.  Then I proceeded to delete all three folders:  Cache/WTF/Interface and restarted my game to allow new fresh copies of those folders to be established.

I moved my WTF information without the savedvariables back into the new WTF folder, but did not include the addons from the old Interface folder.  Then I reinstalled a fresh copy of your UI addon and launched the game.  I reset my UI with the fresh install so that most of what I wanted was reestablished to my liking.  Then installed fresh copies of all my addons that I had been using instead of copying any of those over from the old folder.

Launched the game and everything seemed faster and less choppy whenever I entered an instance, Torghast, or the Maw.  I even did one of the world bosses I had been planning on doing.  Everything seemed to be super smooth and no hang ups even in the world boss fight where I was healing on my resto shaman (sometimes this is choppy anyway due to the crowd).

So far since all this, I've done 2 LFRs, more world bosses and numerous elite fights with lots of things firing off with ground effects going nuts.  No stutters and no problem with responses from my UI usage that plagued me before.

Somewhere along the line something changed but I have no idea what.  I tend to do fresh installs once every month or so just to get rid of strings that are left behind when changes are made with patches and updates of addons.  I have no idea why all of a sudden I had issues when I had been using your UI for well over a year or so.  I suspect orphan strings/threads from old things not dumped with updates and such.  However, I have no way to pin point any one thing, which is why I posted all this so you can see what actions I finally took to clear my UI problem.

**Comment by lynspottery** [comment]
FYI:  Here is my setup so you can see what I am using.  My pc is a special build my technician put together for me rather than a prebuilt purchased from some random computer company.

Intel Core i7-10700K Comet Lake 3.8GHz Eight-Core
ASUS Z490-A Prime Intel LGA 1200 ATX Motherboard
G.Skill Aegis 16GB 2 x 8GB) DDR4-2400 PC4-19200 CL
Samsung 970 EVO+ 1TB SSD V-NAND M.2 2280 PCIe NVMe
Cooler Master Hyper 212 RGB Black Universal CPU Co
Corsair Enthusiast Series TX850 V2 850W ATX12V v2.31/EPS12V v2.92 80 Plus Bronze Certified Active PFC High Performance Power Supply

**Comment by ls-** [comment]
That's super weird, ngl, but good that it's resolved ☺
I'm currently working on the profile import/export feature, so in the future it should be easier to keep your settings even after you do cleanups like that.
Closing this one then. Good luck! <3
