### ISSUE TITLE
Combat option "Unit Frame Mouseover Cast" not working

### ISSUE THREAD

**Issue by usingvar** [ls-/ls_UI#67]
In the last build, blizzard added this option in Interface -> Combat, which isn't working with this addon in particular. If i disable the addon, the option works fine.
When i mouseover a target, it shows the error: You have no target.

**Comment by ls-** [comment]
It's most likely an oUF issue, but before fixing it there, I'll have to figure out how it works first T_T

Thanks.

**Comment by usingvar** [comment]
No problem, take you time. Thank you for creating the addon.
