### ISSUE TITLE
turning off player castbar breaks loading lsui

### ISSUE THREAD

**Issue by ShuShinigami** [ls-/ls_UI#69]
Message: ...terface/AddOns/ls_UI/embeds/oUF/elements/castbar.lua:553: attempt to call global 'PetCastingBarFrame_OnLoad' (a nil value)
Time: Fri Oct 28 19:00:13 2022
Count: 1
Stack: ...terface/AddOns/ls_UI/embeds/oUF/elements/castbar.lua:553: attempt to call global 'PetCastingBarFrame_OnLoad' (a nil value)
[string "@Interface/AddOns/ls_UI/modules/unitframes/core.lua"]:191: in function `For'
[string "@Interface/AddOns/ls_UI_Options/unitframes/castbar.lua"]:41: in function <...nterface/AddOns/ls_UI_Options/unitframes/castbar.lua:37>
[string "=[C]"]: ?
[string "@Interface/AddOns/Decursive/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Decursive/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:827: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:649>
[string "=[C]"]: ?
[string "@Interface/AddOns/Decursive/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...face/AddOns/Decursive/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Decursive/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Decursive/Libs/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua"]:64: in function <...ve/Libs/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua:53>

Locals: <none>

**Comment by ls-** [comment]
Ugh, got it. It's this addon's bug, but I'm also a dev of where it's breaking. Thanks.
