### ISSUE TITLE
target/focos target castbar Can't move it?

### ISSUE THREAD

**Issue by arksbio** [ls-/ls_UI#70]
It's a really cool ui.

I've just run into a couple of little problems

It's about the target and the target's castbar underneath the frame

It's fixed. I prefer the castbar to be located up the frame.

Alternatively, i need the option to activate the Blizzard Default castbar from the Target and focus target options.

Can you help me with this?

**Comment by ls-** [comment]
Hi!

Generally, it's not the right place to ask this kind of questions, Discord is a much better place for it 😁 

>It's a really cool ui.

Thanks!

>It's fixed. I prefer the castbar to be located up the frame.

Go to `/LSUI` > `Unit Frames` > `Target Frame` > `Castbar` > there check `Detach from Frame`, and then position it wherever you need it via movers/anchors.

![image](https://user-images.githubusercontent.com/2725970/199295670-270f3b0b-855b-4bdd-9412-4bc53df6c3e4.png)

You'll have to adjust the position of the unit frame auras, but it's done in the `Auras` section nearby, you'll need to adjust `yOffset` in there.

And the end result should look like this: 

![image](https://user-images.githubusercontent.com/2725970/199296184-d9d2adb9-4fde-462a-bd35-a3b81152390a.png)
