### ISSUE TITLE
Action Bars Can't Be Unlocked

### ISSUE THREAD

**Issue by dembro27** [ls-/ls_UI#71]
Hi! Great addon, I started using it after the prepatch arrived. I've noticed one problem and have one enhancement request, so I'll open a separate issue for each.

The problem is that action bars seem to be stuck in the locked status. I must use a modifier key to move abilities, and when I click an ability to start dragging it, it will attempt to use the ability (I guess it's set up to cast on key down?) If I go into Options -> Action Bars -> Lock ActionBars and uncheck it, after a /reloadui, it will be checked again.

**Comment by ls-** [comment]
Hi! I chose to do it at the start of the prepatch due to some issues with action buttons. I'll revert this in the next update. Dw <3
