### ISSUE TITLE
Wrong Itemlevel with Heirlooms in Charakter Info

### ISSUE THREAD

**Issue by Valoriaz** [ls-/ls_UI#75]
![image](https://user-images.githubusercontent.com/78284376/225498003-859a020a-f62f-47d2-a3fe-5f5ee94de8db.png)
![image](https://user-images.githubusercontent.com/78284376/225498049-2751240f-fcd0-4922-b13b-dd4e7212a3da.png)

**Comment by ls-** [comment]
Hmmm.. I'll look into it 🤔

**Comment by ls-** [comment]
It should be fixed in 100100.03, I'll release it in a couple of days. Better late than never 😅
